spring:
  application:
    name: shoesShopRefactor
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

    logging:
      config: classpath:logback-spring-local.xml


datasource:
  mysql:
    url: jdbc:mysql://127.0.0.1:3306/shoe_refactor
    username: ${USERNAME}
    password: ${PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

#  redis:
#    host: localhost
#    port: 6379
#    password:

